### ISSUE TITLE
Donations that include decimals are not taken into account

### ISSUE THREAD

**Issue by ffyte** [dustinslane/Subathon-Evolved-Releases#3]
When donating sums that are not full dollars, or editing the donation total, it doesn't accept (or take into account) non-integer totals.

Bits are counted correctly, however.

**Comment by dustinslane** [comment]
this should be fixed as of 4.5.3

**Comment by ffyte** [comment]
Still can't use decimals when editing the donation amount. If I type a period or comma it does nothing.

**Comment by dustinslane** [comment]
Sorry my tired brain has misread this and thought it was done

**Comment by robertzonn** [comment]
still not including decimals
